### ISSUE TITLE
OR ları engelle

### ISSUE THREAD

**Issue by eesmerdag** [eesmerdag/v1.0.1#4]

**Comment by eesmerdag** [comment]
@memregursoy şu an için çalışması lazım bilgin olsun abi.

**Comment by memregursoy** [comment]
@eesmerdag çalışması lazım derken başarıyla engelledik mi yani? :)

**Comment by eesmerdag** [comment]
@memregursoy evet bugün commit ledim.Ben test ettiğimde sorun bulamadım.OR olanları clean metodunda yok ediyoruz :D Bu gece de şu özel durum vardı ya onu yapıp commitlerim.

**Comment by memregursoy** [comment]
@eesmerdag tamamdir bu issue'yu da hayirlisiyla kapatiyorum o zaman :)
